### ISSUE TITLE
No error on failed tile server access

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#121]
I was having some internet connectivity issues, and I noticed that when I had no internet access, the tiles failed to download but there was no error. The drawing seems to know some information about the tile source (from cached data?) but the tiles are empty. It would be nice if the call to retrieve tiles (geoviews I guess) came back with at least some sort of warning.   
  
I'll also say that once my internet was restored and I redrew the annotator (without re-instantiating the annotator), it DID pick up the tile service. So I guess the tiles are brought down (and cached it seems) during each call to visualize. I thought that was interesting.  
  
![tiles](https://user-images.githubusercontent.com/15659110/41556872-9075b7f2-7301-11e8-924e-e6e7fa95703d.PNG)

**Comment by jbednar** [comment]
I would expect there to be error messages on the JavaScript console in this case.  How to get to that console depends on your OS and browser, but once you do you should probably see some messages about URL requests that failed.

**Comment by kcpevey** [comment]
As a user have no JS knowledge and only barely know that somehow, deep down inside, its used in this application. I would never think to look for a console, nor do I know where that would even be (windows/Chrome). Regardless of my personal knowledge, our end user won't even know that JS has anything to do with their usage.

**Comment by jbednar** [comment]
For Windows/Chrome, the JS console is accessible as Ctrl + Shift + J.  There's a similar situation on just about any webpage -- if you leave the JS console open and browse your usual sites, you can often see various error messages that browser authors have generally decided are not worth bothering the user about.  

Officially, it's up to the browser and the user what they would like to do with such messages, but in this case we could consider if there are ways we could make this condition more obvious.  What behavior would you like to see?  BokehJS is issuing the request for each tile, and it's failing from within JavaScript, which is why the messages would be on the JS console by default.  Would you want a Python error message (in the notebook), if that's possible?  Would you want the tiles to get substituted with some sort of dummy image (e.g. a red X or one just saying 404?), so that you can tell something's missing?  That seems conceivable, but I'm not sure if it will make it clear to the user what they need to do.  

Personally, I think I'd prefer the current behavior to any of the above options, so that I can still use plots even when not connected to the internet, but it'c certainly worth getting some other votes!

**Comment by philippjfr** [comment]
I cannot see how we can have errors fetching the tiles bubble back up to Python. The only thing that can conceivably be done is validating the URL ahead of time by firing off a request for a tile from Python, that seems like something that could be done by whatever code is supplying the tile source URL. GeoViews provides a fairly diverse set of tile sources already and imo shouldn't be involved in validating user supplied URLs through some ad-hoc scheme that can fail for a variety of reasons, e.g. poor network connectivity.

**Comment by jbednar** [comment]
I don't think the proposal was for the purpose of validation, but for making it more obvious that network connectivity is the problem.  In any case, I don't know of any good mechanism for signaling that error back to Python, and in any case I think I'd personally rather have the plots have no background tiles but otherwise be usable in that case, rather than an error.

**Comment by kcpevey** [comment]
I'm in agreement with @jbednar . The current functionality of no background tiles but an otherwise useful image seems like the best available option here. I can accept that there will be no warnings. I'm ok with closing this.
