### ISSUE TITLE
Disabling param/parambokeh widgets

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#179]
Is it possible to set a param widget as `disabled` or `editable` or some equivalent?  This would be different than precendence, which causes the widget to hide entirely. I want to display the widget, but I want it to be greyed out until I pull a trigger using another widget. I don't see any options for this in the docs and perhaps its a concept that becomes an option after we have widget interactions/dependencies?

**Comment by jbednar** [comment]
Right now, you can make it be `readonly=True`, which will make it show up as a string representation rather than as a widget.  But yes, after we have widget dependencies, it would make sense for the editability to be contingent on another widget's value.  Not sure how we'd express that, but it's reasonable...

**Comment by kcpevey** [comment]
Hmmm... I'm trying to decide if that will work for me. Is there any way to set font color on the widgets?

**Comment by jbednar** [comment]
I would bet there is a way using CSS, but it would take some investigation.

**Comment by kcpevey** [comment]
I think the `param.depends` work will take care of this sufficiently.
