### ISSUE TITLE
Getting the example notebooks

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#205]
I was tracking down a bug in the annotators, but I had made changes to `Annotators.ipynb` so I needed a fresh copy. `git pull` indicated I was already up to date, which wasn't true. I deleted all of the user guide notebooks and `git pull` still insists I'm up to date. I think `earthsim-examples` just copies from the local repo so that's not helpful. I tried to get the notebook from the github repo website, but I can't seem to download the notebook as text instead of html garbage.   
  
Is there any reason why the user-guide wouldn't be included the `git pull`?

**Comment by jbednar** [comment]
The git pull command will update your local clone of the repository, where the user guide is in `EarthSim/examples/user-guide`.  By design, pulling will *not* affect an existing `earthsim-examples`; those go outside the repo so that your changes to them won't affect your repo by default.  (Otherwise you wouldn't be able to pull new changes to anything, if you'd ever run a notebook and not reverted the resulting changes to it.)  To get a new copy of the notebooks, you need to run the example-fetching command again *after* pulling in your repo, or just go snooping in your local clone of the repo in the examples directory.

From github, you can get the absolute latest copy (or any prior version) of the notebooks by navigating to it in the code browser then clicking "Raw":
![image](https://user-images.githubusercontent.com/1695496/44607139-fae40700-a7b4-11e8-9e08-4bf4b5ffc395.png)
You can then right click that and save it, though you'll often have to remove the bogus ".txt" that browsers on some OSs will put on it.

**Comment by kcpevey** [comment]
Thanks. Best I can tell, my .git metadata was broken somehow because the git pull was updating the local copy. I ended up trashing the whole repo and starting fresh.   
  
And I'm glad to know that "Raw" trick too!
