### ISSUE TITLE
Dynamic table of lat/lon on path/polygon elements

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#26]
I want to have a dynamic table including the latitude and longitude of the points on the drawn Path or Polygon. I think there might be two basic approaches - 

1) Add two additional columns to the PolyAnnotator table (modify load_table and poly_columns?). Information that is static across all points in the poly would just be repeated for every point row in the poly. I question whether this is doable since the dynamic highlighting then becomes hairy (should one row on the table highlight just that point or automatically highlight the entire table). It's going to get confusing mixing the point and poly data.   
2) Add a separate table that ONLY includes the lat/lon data for the highlighted poly. So if nothing is highlighted on the drawing, the table doesn't contain anything.   
  
I've spent several days and several different approaches trying to get this (or anything similar) to work for me and have had no success. Can someone weigh in on what might be the best direction for me to take - either one of the above suggestions or something else entirely. Then perhaps I can narrow in my efforts. Thanks!

**Comment by kcpevey** [comment]
Can anyone weigh in on my approach to this? If the annotators get generalized, the direction of my approach may change completely.

**Comment by philippjfr** [comment]
This will require some consideration, particularly considering potential refactors/changes to the ``Annotators``. The main obstacle here and elsewhere will be whether we can find a nice mechanism to share datasources between the polygon datastructure and the annotated values. Currently the main complexity in the ``PolyAnnotator``, which is not shared by the ``PointAnnotator`` is that we have to manually sync the labels and the polygon/polyline data with the associated labels, while the point data can simply share the same underlying data source. 

This is because the mechanism used by HoloViews to share datasources is to check whether the ``.data`` attribute on the elements has the same identity, which is no problem for ``Points`` and ``Table`` but is currently not entirely straightforward for ``Polygons``/``Path`` elements and a ``Table``.

Once we have solved that problem we should fairly easily be able to display the full set of lat/lons or add some additional column that describes the lats/lons for each polygon/line.

**Comment by jlstevens** [comment]
> ... this is because the mechanism used by HoloViews to share datasources is to check whether the .data attribute on the elements has the same identity

This has generally worked better than I expected but maybe we should consider a way to extend this mechanism as required in HoloViews. The core of it is a boolean predicate to decide whether something 'is the same thing' or not.
