### ISSUE TITLE
Annotators vs Holoviews dynamic tables

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#36]
Question: what is the main difference between the dynamic tables with the annotators and Holoviews dynamic tables?  Is it that the source data for the annotator tables use the streams from the drawing tools?

**Comment by jlstevens** [comment]
> Is it that the source data for the annotator tables use the streams from the drawing tools?

@philippjfr can correct me if I am wrong, but that is my understanding of how it works.

**Comment by philippjfr** [comment]
To clarify there are two approaches to sharing the data between two plots:

1. By sharing the underlying bokeh ``ColumnDataSource`` two different plots e.g. a table and a set of points are synced directly client-side in the JS code, this is simplest but in HoloViews this requires the two elements to share their underlying ``.data``, because that's how HoloViews figures out if two plots should share a datasource. This is the mechanism used by the ``PointAnnotator`` and is by far the simplest approach.

2. By sending both the polygon/polyline data and the annotated values back to python and synthesizing a table from the two datasources we can create a view of the annotated polygons/polylines. This is very complex and requires some tricks to make it work and sync appropriately. This is what is used by the ``PolyAnnotator`` because there is currently no easy way to share a bokeh ``ColumnDataSource`` between the polygon plot and the table plot. In theory it should be possible to share them but I think we might need a better mechanism at the HoloViews level to make this work correctly.

**Comment by philippjfr** [comment]
We have no switched entirely to approach number 1 for the annotators, so I'll close this issue.
