### ISSUE TITLE
datashaded TriMesh.edgepaths boundary detection source

### ISSUE THREAD

**Issue by kcpevey** [pyviz/EarthSim#64]
I see that `datashade(tri_mesh.edgepaths)` colors the boundary edges a different color. Where is it getting boundary detection from?

**Comment by jbednar** [comment]
I'm not sure what you mean, as datashade doesn't directly have any knowledge of which edges are on the boundary, but perhaps this is just an artifact of the default coloring by number of overlapping pixels -- interior edges may be drawn twice, due to being shared with two triangles, and boundary edges only once.  You can turn that behavior off using a single-color colormap (cmap=['blue']) or using an aggregator of `ds.any()` (where it no longer counts the overlapping pixels).

**Comment by kcpevey** [comment]
Got it. Thanks! I just wanted to make sure it was an artifact and not a more intelligent process (in which case, I'd utilize it :) )
